version: '3'

services:
  ntopng:
    image: "mcncclovett/ntopng"
    command: ["/usr/local/bin/ntopng", "--local-networks", "10.0.0.0/8", "--redis", "localhost"]
    #ports:
    # - "3000:3000"
    network_mode: "host"
