version: '3'

services:
  ntopng:
    image: "mcncclovett/ntopng"
    command: ["redis",  "/etc/redis.conf", ";", "ntopng", "--local-networks", "10.0.0.0/8"]
    #ports:
    # - "3000:3000"
    network_mode: "host"
